// if else 
let marks=101

if (marks>=90 && marks<=100){
    console.log("A PLUS GRADE")
}else if (marks>=80 && marks<90){
    console.log("A GRADE")
}
else if (marks>=70 && marks<80){
    console.log("B GRADE")
}
else if (marks>=60 && marks<70){
    console.log("C GRADE")
}
else if (marks>100 || marks<0){
        console.log("THEEK SEI MARKS DAALO CUTIE")
}
else 
console.log("fail")

